### ISSUE TITLE
从大佬的vue-scan过来的，然后又发现了这个vue的python实现demo

### ISSUE THREAD

**Issue by rjwaltz** [zcf0508/pyvue#3]
虽然没看代码，但是光看截图能看明白确实有点vue那味道了，还引入了slot（当然不是qt的signal-slot😂）
太强了大佬，我也是写了两年python后转到web端，感觉这差距太大了，可以加联系方式么，想向你学习🫡

**Comment by zcf0508** [comment]
这个项目设计得很早期，对 python proxy 和 vue 响应式的理解都还有偏差，只是作为一个试验放在这里。大家一起互相学习。
